version: "3"

services:
  node:
    image: node:16
    container_name: desafio-xp
    tty: true
    stdin_open: true
    command: 'bash'
    restart: always
    working_dir: /app
    volumes:
      - ./:/app
    depends_on:
      - db
    ports:
      - 3000:3000
    environment:
      PORT: 3000
      MYSQL_USER: root
      MYSQL_PASSWORD: password
      MYSQL_HOST: desafio-xp-db
      MYSQL_DATABASE: stocks_xp
      JWT_SECRET: secret

  db:
    container_name: desafio-xp-db
    image: mysql:8.0.21
    restart: always
    ports:
      - 3306:3306
      - 33060:33060
    environment:
      MYSQL_ROOT_PASSWORD: password